/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BUS.KhachHangBUS;
import BUS.UserBUS;
import DTO.nhanvienDTO;
import DAO.nhanvienDAO;
import BUS.nhanvienBUS;
import DTO.KhachHang;
import javax.swing.JOptionPane;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MY PC
 */
public class KhachHangGUI extends javax.swing.JPanel {
    DefaultTableModel model =new DefaultTableModel();
    JLabel suaBtn;
    CheckLoi cl = new CheckLoi();
    /**
     * Creates new form nhanvienGUI
     */
    public KhachHangGUI() {
        initComponents();
        FormatTable render = new FormatTable();
        render.formatTablenoIcon(tablenhanvien);
        inTable();
        nhanvienBUS bus = new nhanvienBUS();
        txtIdkh.setText(bus.loadIdpn());
        txtIdkh.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTimkiem = new javax.swing.JTextField();
        combobox = new javax.swing.JComboBox();
        timkiemIcon = new javax.swing.JLabel();
        docBtn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablenhanvien = new javax.swing.JTable();
        thoigianbatdauLb2 = new javax.swing.JLabel();
        maGiamLb = new javax.swing.JLabel();
        txtIdkh = new javax.swing.JTextField();
        txtHo = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        thoigianbatdauLb = new javax.swing.JLabel();
        thoigianketthucLb = new javax.swing.JLabel();
        thoigianbatdauLb4 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        changeBtn = new javax.swing.JLabel();
        addBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbBox = new javax.swing.JComboBox();

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(950, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 650));

        txtTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimkiemActionPerformed(evt);
            }
        });

        combobox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        combobox.setForeground(new java.awt.Color(0, 51, 255));
        combobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Họ", "Tên", " " }));

        timkiemIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-35.png"))); // NOI18N
        timkiemIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timkiemIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timkiemIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                timkiemIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                timkiemIconMouseExited(evt);
            }
        });

        docBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-process-35.png"))); // NOI18N
        docBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        docBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                docBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                docBtnMouseExited(evt);
            }
        });

        tablenhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên chương trình", "Thời gian bắt đầu", "Thời gian kết thúc", "Trạng thái", "Nội dung", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablenhanvien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablenhanvien.setRowHeight(20);
        tablenhanvien.setShowVerticalLines(false);
        tablenhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablenhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablenhanvien);

        thoigianbatdauLb2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        thoigianbatdauLb2.setForeground(new java.awt.Color(255, 102, 0));
        thoigianbatdauLb2.setText("Giới tính");

        maGiamLb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        maGiamLb.setForeground(new java.awt.Color(255, 102, 0));
        maGiamLb.setText("ID khách hàng");
        maGiamLb.setMaximumSize(new java.awt.Dimension(81, 25));
        maGiamLb.setPreferredSize(new java.awt.Dimension(81, 25));

        txtIdkh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtIdkh.setPreferredSize(new java.awt.Dimension(6, 25));
        txtIdkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdkhActionPerformed(evt);
            }
        });

        txtHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoActionPerformed(evt);
            }
        });

        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });

        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Họ khách");

        thoigianbatdauLb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        thoigianbatdauLb.setForeground(new java.awt.Color(255, 102, 0));
        thoigianbatdauLb.setText("Tên khách");

        thoigianketthucLb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        thoigianketthucLb.setForeground(new java.awt.Color(255, 102, 0));
        thoigianketthucLb.setText("Phone");
        thoigianketthucLb.setPreferredSize(new java.awt.Dimension(124, 25));

        thoigianbatdauLb4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        thoigianbatdauLb4.setForeground(new java.awt.Color(255, 102, 0));
        thoigianbatdauLb4.setText("Email");

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        changeBtn.setBackground(new java.awt.Color(255, 153, 0));
        changeBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        changeBtn.setForeground(new java.awt.Color(255, 255, 255));
        changeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-change-50.png"))); // NOI18N
        changeBtn.setText("Sửa");
        changeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeBtn.setOpaque(true);
        changeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changeBtnMouseExited(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(255, 153, 0));
        addBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add-50.png"))); // NOI18N
        addBtn.setText("Thêm");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.setOpaque(true);
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addBtnMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-account-30.png"))); // NOI18N
        jLabel1.setText("Quản lý khách hàng");

        cbBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ", "Khác" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(709, 709, 709)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(changeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timkiemIcon)
                        .addGap(341, 341, 341)
                        .addComponent(docBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(thoigianbatdauLb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maGiamLb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdkh, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtHo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(txtTen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                                .addGap(93, 93, 93)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(thoigianketthucLb, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(thoigianbatdauLb4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(thoigianbatdauLb2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdkh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(maGiamLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(thoigianbatdauLb4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thoigianketthucLb, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thoigianbatdauLb, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thoigianbatdauLb2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeBtn)
                            .addComponent(cbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timkiemIcon)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(docBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdkhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdkhActionPerformed

     public void reset()//reset txt field
    {
        txtHo.setText("");
        txtTen.setText("");
        txtphone.setText("");
        txtemail.setText("");       
        txtTimkiem.setText("");
        KhachHangBUS bus = new KhachHangBUS();
        txtIdkh.setText(bus.loadIdKhachHang());
        inTable();
    }
    
    public void inTable()//doc du lieu in vao table
    {
        try
        {
        //render();
        KhachHangBUS nvbus = new KhachHangBUS();
        nvbus.docKhachHang();
            int rowCount = model.getRowCount();//remove all row
            for (int i = rowCount - 1; i >= 0; i--) 
            {
                model.removeRow(i);
            }
        Vector header = new Vector();
        header.add("ID Khách");
        header.add("Họ");
        header.add("Tên");
        header.add("Phone");
        header.add("Email");
        header.add("Giới tính");
        header.add("Tổng tiền mua");
        if (model.getRowCount()==0)
            { 
                model=new DefaultTableModel(header,0);
            } 
        for(KhachHang nv : KhachHangBUS.dstongnv)
        {
                Vector row = new Vector();
                row.add(nv.getIdKh());
                row.add(nv.getHo());
                row.add(nv.getTen());
                row.add(nv.getSdt());
                row.add(nv.getEmail());                
                row.add(nv.getGioitinh());                
                row.add(nv.getTongtiendamua());
                
                model.addRow(row);
        }
        //add model to jtable
        tablenhanvien.setModel(model);
        
        } catch(Exception e)
        {
            System.out.println(e);
            System.out.println("Lỗi đọc KhachHang");
        }
    }
    public boolean kiemtra()
    {
        if(txtIdkh.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Chưa nhập mã Khach Hang");
            txtIdkh.requestFocus();
            return false;
        }
        
        else if (txtHo.getText().equals("")  )
        {
            JOptionPane.showMessageDialog(null, "Chưa nhập Họ Khach Hang");
            txtHo.requestFocus();
            return false;
        }
        else if(cl.kiemtraSokitu(txtHo.getText(), 30)==false)
        {
            JOptionPane.showMessageDialog(null, "Họ Khach Hang không dc quá 30 kí tự");
            txtHo.requestFocus();
            return false;
        }
        else if (txtTen.getText().equals("")  )
        {
            JOptionPane.showMessageDialog(null, "Chưa nhập tên Khach Hang");
            txtTen.requestFocus();
            return false;
        }
        else if(cl.kiemtraSokitu(txtTen.getText(), 30)==false)
        {
            JOptionPane.showMessageDialog(null, "Tên Khach Hang không vượt quá 30 ký tự");
            txtTen.requestFocus();
            return false;
        }
        
        else if (txtemail.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null, "Chưa nhập email");
            txtemail.requestFocus();
            return false;
        }
        else if(cl.kiemtraEmail(txtemail.getText()) == false)
        {
            JOptionPane.showMessageDialog(null, "Email không hợp lệ");
            txtemail.requestFocus();
            return false;
        }
        else if (txtphone.getText().equals(""))
        {

            JOptionPane.showMessageDialog(null, "Chưa nhập số điện thoại");
            txtphone.requestFocus();
            return false;
        }
        else if(cl.kiemtraSDT(txtphone.getText())==false)
        {
            JOptionPane.showMessageDialog(null, "Số điện thoại không hợp lệ (11 số) + số 0 đầu");
            txtphone.requestFocus();
            return false;
        }
        else if(cl.kiemtraSo(txtphone.getText())==false)
        {
            JOptionPane.showMessageDialog(null, "Số điện thoại không hợp lệ (nhập số)");
            txtphone.requestFocus();
            return false;
        }
        return true;
    }
    
    public void hienthi()
    {
        JFrame j = new JFrame();
        j.setSize(1000,700);
        j.setLayout(null);
        JPanel p =new KhachHangGUI();
        p.setBounds(0, 0, 950, 410);
        
        //j.add(g);
        //j.pack();
        j.add(p);
        j.setVisible(true);
    }
    
    public void timkiem(ArrayList<KhachHang> arr)
    {
        //hien thong tin tim kiem
    int rowCount = model.getRowCount();//remove all row
            for (int i = rowCount - 1; i >= 0; i--) {
                model.removeRow(i);
            }
        Vector header = new Vector();
        header.add("ID Khách");
        header.add("Họ");
        header.add("Tên");
        header.add("Phone");
        header.add("Email");
        header.add("Giới tính");
        header.add("Tổng tiền mua");
        if (model.getRowCount()==0)
            { 
                model=new DefaultTableModel(header,0);
            } 
        for(KhachHang nv : arr)//duyet arr chua cac ket qua tìm kiếm
        {
                Vector row = new Vector();
                row.add(nv.getIdKh());
                row.add(nv.getHo());
                row.add(nv.getTen());
                row.add(nv.getSdt());
                row.add(nv.getEmail());
                row.add(nv.getGioitinh());
                row.add(nv.getTongtiendamua());
                model.addRow(row);
        }
        //add model to jtable
        tablenhanvien.setModel(model);
    }
    
    
    
    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked

        KhachHangBUS nvbus = new KhachHangBUS();
        nvbus.docKhachHang();
        try
        {
            KhachHang nvdto = new KhachHang();
            boolean ok = false;
            
            if(kiemtra())
            {
                ok = true;
            }
            if(ok)
            {

                KhachHang nv = new KhachHang();
                nv.setIdKh(txtIdkh.getText());
                nv.setHo(txtHo.getText());
                nv.setTen(txtTen.getText());
                nv.setSdt(txtphone.getText());
                nv.setEmail(txtemail.getText());
                nv.setGioitinh((String)cbBox.getSelectedItem());
                nv.setTongtiendamua(0);
                nvbus.themKhachHang(nv);

                //Jtable
                Vector header = new Vector();
                header.add("ID Khách");
                header.add("Họ");
                header.add("Tên");
                header.add("Phone");
                header.add("Email");
                header.add("Giới tính");
                header.add("Tổng tiền mua");

                if (model.getRowCount() == 0) 
                {
                    model = new DefaultTableModel(header, 0);
                }
                Vector row = new Vector();
                row.add(nv.getIdKh());
                row.add(nv.getHo());
                row.add(nv.getTen());
                row.add(nv.getSdt());
                row.add(nv.getEmail());
                row.add(nv.getGioitinh());
                row.add(nv.getTongtiendamua());
                model.addRow(row);
                //add model to jtable
                tablenhanvien.setModel(model);
                //                    System.out.println(begin);
                //                    System.out.println(end);
                JOptionPane.showMessageDialog(null, "Thêm khách hàng thành công");
                
                reset();

            }
        } catch (Exception e)
        {   
            System.out.println(e);
            System.out.println("Lỗi thêm nhân viên");
            
        }
    }//GEN-LAST:event_addBtnMouseClicked

    private void addBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseEntered
        // TODO add your handling code here:
        //addbtn
        addBtn.setBackground(Color.blue);
    }//GEN-LAST:event_addBtnMouseEntered

    private void addBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseExited
        // TODO add your handling code here:
        addBtn.setBackground(new Color(255, 153, 0));
    }//GEN-LAST:event_addBtnMouseExited

    private void changeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeBtnMouseClicked
        // TODO add your handling code here:
        //sua btn click
        try
        {
            if(tablenhanvien.getSelectionModel().isSelectionEmpty())//neu khong chọn row trong table
            {
                JOptionPane.showMessageDialog(null, "Chưa chọn mã cần sửa");
            } else
            {
                int  i=tablenhanvien.getSelectedRow();
                KhachHang nv=new KhachHang();

                nv.setIdKh(txtIdkh.getText());
                nv.setHo(txtHo.getText());
                nv.setTen(txtTen.getText());
                nv.setSdt(txtphone.getText());
                nv.setEmail(txtemail.getText());
                nv.setGioitinh((String)cbBox.getSelectedItem());
                //cap nhập dsgg
                KhachHangBUS nvbus = new KhachHangBUS();
                nvbus.suaKhachHang(nv);
                //System.out.println(ChuongTrinhGiamBUS.dsgiamgia.get(i));
                //truyen vao table bang arr cua bus
                model.setValueAt(nv.getIdKh(), i, 0);
                model.setValueAt(nv.getHo(), i, 1);
                model.setValueAt(nv.getTen(), i, 2);
                model.setValueAt(nv.getSdt(), i, 3);
                model.setValueAt(nv.getEmail(), i, 4);
                model.setValueAt(nv.getGioitinh(), i, 5);
                model.setValueAt(nv.getTongtiendamua(), i, 6);

                tablenhanvien.setModel(model);
                JOptionPane.showMessageDialog(null, "Sửa thành công");
                reset();
            }
        } catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_changeBtnMouseClicked

    private void changeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeBtnMouseEntered
        // TODO add your handling code here:\
        changeBtn.setBackground(Color.blue);
    }//GEN-LAST:event_changeBtnMouseEntered

    private void changeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeBtnMouseExited
        // TODO add your handling code here:
        changeBtn.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_changeBtnMouseExited

    private void txtTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimkiemActionPerformed

    private void timkiemIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiemIconMouseClicked
        // TODO add your handling code here:
        KhachHangBUS nvbus = new KhachHangBUS();
        if(combobox.getSelectedItem().equals("All"))
        {
            //thêm txt cần tìm vào hàm timtheo... của bus sau đó truyền hàm đó vào hàm timkiem ở gui de in len jtable
            timkiem(nvbus.timtheoAll(txtTimkiem.getText()));
        }
        if(combobox.getSelectedItem().equals("Họ"))
        {
            //thêm txt cần tìm vào hàm timtheo... của bus sau đó truyền hàm đó vào hàm timkiem ở gui de in len jtable
            timkiem(nvbus.timtheoFname(txtTimkiem.getText()));
        }
        if(combobox.getSelectedItem().equals("Tên"))
        {
            //thêm txt cần tìm vào hàm timtheo... của bus sau đó truyền hàm đó vào hàm timkiem ở gui de in len jtable
            timkiem(nvbus.timtheoLname(txtTimkiem.getText()));
        }
    }//GEN-LAST:event_timkiemIconMouseClicked

    private void timkiemIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiemIconMouseEntered
        // TODO add your handling code here:
        timkiemIcon.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/search.png");
        timkiemIcon.setIcon(logo);
    }//GEN-LAST:event_timkiemIconMouseEntered

    private void timkiemIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiemIconMouseExited
        // TODO add your handling code here:
        timkiemIcon.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-search-35.png");
        timkiemIcon.setIcon(logo);
    }//GEN-LAST:event_timkiemIconMouseExited

    private void docBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docBtnMouseClicked
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_docBtnMouseClicked

    private void docBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docBtnMouseEntered
        // TODO add your handling code here:
        docBtn.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-process-35 (1).png");
        docBtn.setIcon(logo);
    }//GEN-LAST:event_docBtnMouseEntered

    private void docBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docBtnMouseExited
        // TODO add your handling code here:
        docBtn.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-process-35.png");
        docBtn.setIcon(logo);
    }//GEN-LAST:event_docBtnMouseExited

    private void tablenhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablenhanvienMouseClicked
        // TODO add your handling code here:
        try
        {
            int  i=tablenhanvien.getSelectedRow();
            if(i>=0)
            {
                txtIdkh.setEditable(false);//ko cho dien mã
                nhanvienDTO nv =new nhanvienDTO();
                //ct = ChuongTrinhGiamBUS.dsgiamgia.get(i);    //goi arr bus lay gia trị
                txtIdkh.setText((String)tablenhanvien.getValueAt(i, 0));
                txtHo.setText((String)tablenhanvien.getValueAt(i, 1));
                txtTen.setText((String)tablenhanvien.getValueAt(i, 2));
                txtphone.setText(String.valueOf(tablenhanvien.getValueAt(i, 3)));
                txtemail.setText((String)tablenhanvien.getValueAt(i, 4));
                cbBox.setSelectedItem(tablenhanvien.getValueAt(i, 5));
                //format theo kiểu của jdatechooser

            }
        } catch (Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_tablenhanvienMouseClicked

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        


        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void txtHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoActionPerformed
        
// TODO add your handling code here:
    }//GEN-LAST:event_txtHoActionPerformed

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
              // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    public static void main(String[] args) 
    {
        JFrame j = new JFrame();
        j.setSize(960,700);
        j.setLayout(null);
        JPanel p =new KhachHangGUI();
        p.setBounds(0, 0, 960, 700);
        //j.add(g);
        //j.pack();
        j.add(p);
        j.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBtn;
    private javax.swing.JComboBox cbBox;
    private javax.swing.JLabel changeBtn;
    private javax.swing.JComboBox combobox;
    private javax.swing.JLabel docBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maGiamLb;
    private javax.swing.JTable tablenhanvien;
    private javax.swing.JLabel thoigianbatdauLb;
    private javax.swing.JLabel thoigianbatdauLb2;
    private javax.swing.JLabel thoigianbatdauLb4;
    private javax.swing.JLabel thoigianketthucLb;
    private javax.swing.JLabel timkiemIcon;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtIdkh;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTimkiem;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
