/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BUS.MonanBUS;
import DTO.nhacungcapDTO;
import BUS.nhacungcapBUS;
import DTO.MonanDTO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MY PC
 */
public class nhacungcapGUI extends javax.swing.JPanel 
{
    JLabel suaBtn;
    DefaultTableModel model =new DefaultTableModel();
    CheckLoi cl = new CheckLoi();
    /**
     * Creates new form nhacungcapGUI
     */
    public nhacungcapGUI() {
        initComponents();
        FormatTable render = new FormatTable();
        render.formatTablenoIcon(tablenhacungcap);
        inTable();
        nhacungcapBUS bus = new nhacungcapBUS();
        txtIdncc.setText(bus.loadIdpn());
        txtIdncc.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        txtIdncc = new javax.swing.JTextField();
        maGiamLb = new javax.swing.JLabel();
        thoigianbatdauLb = new javax.swing.JLabel();
        thoigianketthucLb = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTenncc = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        rightPanel = new javax.swing.JPanel();
        addBtn = new javax.swing.JLabel();
        changeBtn = new javax.swing.JLabel();
        txtTimkiem = new javax.swing.JTextField();
        combobox = new javax.swing.JComboBox();
        timkiemIcon = new javax.swing.JLabel();
        docBtn = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablenhacungcap = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(950, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 650));

        leftPanel.setBackground(new java.awt.Color(0, 255, 204));

        txtIdncc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtIdncc.setPreferredSize(new java.awt.Dimension(6, 25));
        txtIdncc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdnccActionPerformed(evt);
            }
        });

        maGiamLb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        maGiamLb.setForeground(new java.awt.Color(255, 102, 0));
        maGiamLb.setText("Id Nhà Cung Cấp");
        maGiamLb.setMaximumSize(new java.awt.Dimension(81, 25));
        maGiamLb.setPreferredSize(new java.awt.Dimension(81, 25));

        thoigianbatdauLb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        thoigianbatdauLb.setForeground(new java.awt.Color(255, 102, 0));
        thoigianbatdauLb.setText("Email");

        thoigianketthucLb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        thoigianketthucLb.setForeground(new java.awt.Color(255, 102, 0));
        thoigianketthucLb.setText("Phone");
        thoigianketthucLb.setPreferredSize(new java.awt.Dimension(124, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Tên Nhà Cung Cấp");

        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(maGiamLb, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdncc, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thoigianbatdauLb, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thoigianketthucLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenncc, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maGiamLb, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenncc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thoigianbatdauLb, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thoigianketthucLb, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        rightPanel.setBackground(new java.awt.Color(0, 255, 204));

        addBtn.setBackground(new java.awt.Color(255, 153, 0));
        addBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add-50.png"))); // NOI18N
        addBtn.setText("Thêm");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.setOpaque(true);
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addBtnMouseExited(evt);
            }
        });

        changeBtn.setBackground(new java.awt.Color(255, 153, 0));
        changeBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        changeBtn.setForeground(new java.awt.Color(255, 255, 255));
        changeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-change-50.png"))); // NOI18N
        changeBtn.setText("Sửa");
        changeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeBtn.setOpaque(true);
        changeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changeBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(changeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(addBtn)
                .addGap(18, 18, 18)
                .addComponent(changeBtn)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        txtTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimkiemActionPerformed(evt);
            }
        });

        combobox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        combobox.setForeground(new java.awt.Color(0, 51, 255));
        combobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Mã nhà cung cấp", "Tên" }));
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });

        timkiemIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-35.png"))); // NOI18N
        timkiemIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timkiemIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timkiemIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                timkiemIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                timkiemIconMouseExited(evt);
            }
        });

        docBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-process-35.png"))); // NOI18N
        docBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        docBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                docBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                docBtnMouseExited(evt);
            }
        });

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-delete-35.png"))); // NOI18N
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteBtnMouseExited(evt);
            }
        });

        tablenhacungcap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên chương trình", "Thời gian bắt đầu", "Thời gian kết thúc", "Trạng thái", "Nội dung", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablenhacungcap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablenhacungcap.setRowHeight(20);
        tablenhacungcap.setShowVerticalLines(false);
        tablenhacungcap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablenhacungcapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablenhacungcap);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-factory-50.png"))); // NOI18N
        jLabel1.setText("Quản lý nhà cung cấp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(docBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn)
                        .addGap(104, 104, 104))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timkiemIcon)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(timkiemIcon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(docBtn)
                            .addComponent(deleteBtn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdnccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdnccActionPerformed
                 // TODO add your handling code here:
    }//GEN-LAST:event_txtIdnccActionPerformed

    public void reset()//reset txt field
    {
        txtTenncc.setText("");
        txtemail.setText("");
        txtphone.setText("");
        txtTimkiem.setText("");
        inTable();
        nhacungcapBUS bus = new nhacungcapBUS();
        txtIdncc.setText(bus.loadIdpn());
    }
    
    public void inTable()//doc du lieu in vao table
    {
        try
        {
        nhacungcapBUS nccbus = new nhacungcapBUS();
        nccbus.docnhacungcap();
            int rowCount = model.getRowCount();//remove all row
            for (int i = rowCount - 1; i >= 0; i--) 
            {
                model.removeRow(i);
            }
        Vector header = new Vector();
        header.add("ID NCC");
        header.add("Tên nhà cung cấp");
        header.add("Email");
        header.add("Phone");
        
        if (model.getRowCount()==0)
            { 
                model=new DefaultTableModel(header,0);
            } 
        for(nhacungcapDTO ncc : nhacungcapBUS.dsncc)
        {
                Vector row = new Vector();
                row.add(ncc.getIdncc());
                row.add(ncc.getTenncc());
                row.add(ncc.getEmail());
                row.add(ncc.getPhone());
                
                
                model.addRow(row);
        }
        //add model to jtable
        tablenhacungcap.setModel(model);
        
        } catch(Exception e)
        {
            System.out.println(e);
            System.out.println("Lỗi đọc nhà cung cấp");
        }
    }
    
    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        // TODO add your handling code here:
        //add click
        nhacungcapBUS nccbus = new nhacungcapBUS();
        nccbus.docnhacungcap();
        try
        {
            nhacungcapDTO nccdto = new nhacungcapDTO();
            boolean ok = false;
            
            if(kiemtra())
            {
                if(!nhacungcapBUS.dsncc.isEmpty())
                {
                for (nhacungcapDTO a : nhacungcapBUS.dsncc)
                {
                    if (txtIdncc.getText().equals(a.getIdncc())) //kiem tra trùng mã giảm
                    {
                        JOptionPane.showMessageDialog(null, "Mã nhà cung cấp đã tồn tại");
                        ok = false;
                        txtIdncc.setEditable(true);
                        txtIdncc.requestFocus();
                        break;
                    } else {
                        ok = true;
                    }
                }
                } else 
                {
                    ok = true;
                }
            }
            if(ok)// moi thứ ok thì thêm mới
            {
                
                nhacungcapDTO ncc = new nhacungcapDTO();
                ncc.setIdncc(txtIdncc.getText());
                ncc.setTenncc(txtTenncc.getText());
                ncc.setEmail(txtemail.getText());
                ncc.setPhone(txtphone.getText());

                nccbus.themnhacungcap(ncc);

                //Jtable
                Vector header = new Vector();
                header.add("ID NCC");
                header.add("Tên nhà cung cấp");
                header.add("Email");
                header.add("Phone");
                

                if (model.getRowCount() == 0) {
                    model = new DefaultTableModel(header, 0);
                }
                Vector row = new Vector();
                row.add(ncc.getIdncc());
                row.add(ncc.getTenncc());
                row.add(ncc.getEmail());
                row.add(ncc.getPhone());
                
                model.addRow(row);
                //add model to jtable
                tablenhacungcap.setModel(model);
                JOptionPane.showMessageDialog(null, "Thêm nhà cung cấp thành công");
                
                reset();
                
                
               
            }
        } catch (Exception e)
        {
            System.out.println(e);
            System.out.println("Lỗi thêm nhà cung cấp");
        }
    }//GEN-LAST:event_addBtnMouseClicked

    private void addBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseEntered
        // TODO add your handling code here:
        //addbtn
        addBtn.setBackground(Color.blue);
    }//GEN-LAST:event_addBtnMouseEntered

    private void addBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseExited
        // TODO add your handling code here:
        addBtn.setBackground(new Color(255, 153, 0));
    }//GEN-LAST:event_addBtnMouseExited

    private void changeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeBtnMouseClicked
        // TODO add your handling code here:
        //sua btn click
        try
        {
            if(tablenhacungcap.getSelectionModel().isSelectionEmpty())//neu khong chọn row trong table
            {
                JOptionPane.showMessageDialog(null, "Chưa chọn nha cung cap cần sửa");
            } else
            {
                int  i=tablenhacungcap.getSelectedRow();
                nhacungcapDTO ncc=new nhacungcapDTO();
                
                ncc.setIdncc(txtIdncc.getText());
                ncc.setTenncc(txtTenncc.getText());
                ncc.setEmail(txtemail.getText());
                ncc.setPhone(txtphone.getText());
                //cap nhập dsgg
                nhacungcapBUS nccbus = new nhacungcapBUS();
                nccbus.suanhacungcap(ncc);
                //System.out.println(ChuongTrinhGiamBUS.dsgiamgia.get(i));
                //truyen vao table bang arr cua bus
                model.setValueAt(ncc.getIdncc(), i, 0);
                model.setValueAt(ncc.getTenncc(), i, 1);
                model.setValueAt(ncc.getEmail(), i, 2);
                model.setValueAt(ncc.getPhone(), i, 3);
                

                tablenhacungcap.setModel(model);
                JOptionPane.showMessageDialog(null, "Sửa thành công");
                reset();
            }
        } catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_changeBtnMouseClicked

    private void changeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeBtnMouseEntered
        // TODO add your handling code here:\
        changeBtn.setBackground(Color.blue);
    }//GEN-LAST:event_changeBtnMouseEntered

    private void changeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeBtnMouseExited
        // TODO add your handling code here:
        changeBtn.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_changeBtnMouseExited

    private void txtTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimkiemActionPerformed

    private void timkiemIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiemIconMouseClicked
        // TODO add your handling code here:
        nhacungcapBUS nccbus = new nhacungcapBUS();
        if(combobox.getSelectedItem().equals("All"))
        {
            //thêm txt cần tìm vào hàm timtheo... của bus sau đó truyền hàm đó vào hàm timkiem ở gui de in len jtable
            timkiem(nccbus.timtheoAll(txtTimkiem.getText()));
        }
        if(combobox.getSelectedItem().equals("Mã nhà cung cấp"))
        {
            //thêm txt cần tìm vào hàm timtheo... của bus sau đó truyền hàm đó vào hàm timkiem ở gui de in len jtable
            timkiem(nccbus.timtheoMa(txtTimkiem.getText()));
        }
        if(combobox.getSelectedItem().equals("Tên"))
        {
            //thêm txt cần tìm vào hàm timtheo... của bus sau đó truyền hàm đó vào hàm timkiem ở gui de in len jtable
            timkiem(nccbus.timtheoTen(txtTimkiem.getText()));
        }
        

    }//GEN-LAST:event_timkiemIconMouseClicked

    private void timkiemIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiemIconMouseEntered
        // TODO add your handling code here:
        timkiemIcon.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/search.png");
        timkiemIcon.setIcon(logo);
    }//GEN-LAST:event_timkiemIconMouseEntered

    private void timkiemIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiemIconMouseExited
        // TODO add your handling code here:
        timkiemIcon.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-search-35.png");
        timkiemIcon.setIcon(logo);
    }//GEN-LAST:event_timkiemIconMouseExited

    private void docBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docBtnMouseClicked
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_docBtnMouseClicked

    private void docBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docBtnMouseEntered
        // TODO add your handling code here:
        docBtn.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-process-35 (1).png");
        docBtn.setIcon(logo);
    }//GEN-LAST:event_docBtnMouseEntered

    private void docBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docBtnMouseExited
        // TODO add your handling code here:
        docBtn.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-process-35.png");
        docBtn.setIcon(logo);
    }//GEN-LAST:event_docBtnMouseExited

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        // TODO add your handling code here:
        //delete click
        try
        {
            if(tablenhacungcap.getSelectionModel().isSelectionEmpty())//neu khong chọn row trong table
            {
                JOptionPane.showMessageDialog(null, "Chưa chọn nha cung cap cần xóa");
            }
            else   
            {
                int yn = JOptionPane.showConfirmDialog(
                    null,
                    "Bạn có chắc xóa nha cung cap này?",
                    "Are you sure?",
                    JOptionPane.YES_NO_OPTION);
                if (yn == JOptionPane.YES_OPTION)
                {
                    int  i=tablenhacungcap.getSelectedRow();
                    if (i >= 0) 
                    {
                        boolean ok = false;
                        MonanBUS spbus = new MonanBUS();
                        spbus.docDsmonanconban();
                        for(MonanDTO a : MonanBUS.dsmonanconban)
                        {
                            if(a.getIdmon().indexOf(txtIdncc.getText()) >= 0)
                            {
                                ok = false;
                                break;
                            } else ok = true;
                        }
                        System.out.println(ok);
                        System.out.println(txtIdncc.getText());
                        if(ok == true)
                        {
                        nhacungcapDTO ncc = new nhacungcapDTO();
                        ncc.setIdncc(txtIdncc.getText());

                            nhacungcapBUS bus = new nhacungcapBUS();
                            bus.xoanhacungcap(ncc);
                            //remove o table
                            model.removeRow(i);
                            reset();
                            JOptionPane.showMessageDialog(null, "Xóa thành công");
                        } else
                        {
                            JOptionPane.showMessageDialog(null, "Sản phẩm của nhà cung cấp này vẫn còn bán. Không thể xóa.");
                        }
                    }
                

                }
            }

        } catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void deleteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseEntered
        // TODO add your handling code here:
        deleteBtn.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-delete-35 (1).png");
        deleteBtn.setIcon(logo);
    }//GEN-LAST:event_deleteBtnMouseEntered

    private void deleteBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseExited
        // TODO add your handling code here:
        deleteBtn.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-delete-35.png");
        deleteBtn.setIcon(logo);
    }//GEN-LAST:event_deleteBtnMouseExited

    private void tablenhacungcapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablenhacungcapMouseClicked
        // TODO add your handling code here:
        try
        {
            int  i=tablenhacungcap.getSelectedRow();
            if(i>=0)
            {
                txtIdncc.setEditable(false);//ko cho dien mã
                nhacungcapDTO ncc =new nhacungcapDTO();
                //ct = ChuongTrinhGiamBUS.dsgiamgia.get(i);    //goi arr bus lay gia trị
                txtIdncc.setText((String)tablenhacungcap.getValueAt(i, 0));
                txtTenncc.setText((String)tablenhacungcap.getValueAt(i, 1));
                txtemail.setText((String)tablenhacungcap.getValueAt(i, 2));
                txtphone.setText(String.valueOf(tablenhacungcap.getValueAt(i, 3)));
                //format theo kiểu của jdatechooser
                
            }
        } catch (Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_tablenhacungcapMouseClicked

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
              // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    public String hienthiTrangthai(String a) //dieu chinh trang thai là 1 thì hiện dang hoat đong
    {
         return a = "Đang hoạt động";
         
    }
    
    public void timkiem(ArrayList<nhacungcapDTO> arr)
    {
        //hien thong tin tim kiem
    int rowCount = model.getRowCount();//remove all row
            for (int i = rowCount - 1; i >= 0; i--) {
                model.removeRow(i);
            }
        Vector header = new Vector();
        header.add("ID NCC");
        header.add("Tên nhà cung cấp");
        header.add("Email");
        header.add("Phone");
   
       
        if (model.getRowCount()==0)
            { 
                model=new DefaultTableModel(header,0);
            } 
        for(nhacungcapDTO ct : arr)//duyet arr chua cac ket qua tìm kiếm
        {
                Vector row = new Vector();
                row.add(ct.getIdncc());
                row.add(ct.getTenncc());
                row.add(ct.getEmail());
                row.add(ct.getPhone());
                
                model.addRow(row);
        }
        //add model to jtable
        tablenhacungcap.setModel(model);
    }
    
    public boolean kiemtra()
    {
        if(txtIdncc.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Chưa nhập mã nhà cung cấp");
            txtIdncc.requestFocus();
            return false;
        }
        else if(cl.kiemtraSokitu(txtIdncc.getText(), 12) == false)
        {
            JOptionPane.showMessageDialog(null, "Mã nhà cung cấp không vượt quá 12 ký tự");
            txtIdncc.requestFocus();
            return false;
        }
        else if (txtTenncc.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Chưa nhập tên nhà cung cấp");
            txtTenncc.requestFocus();
            return false;
        }
        else if(cl.kiemtraSokitu(txtTenncc.getText(), 30) == false)
        {
            JOptionPane.showMessageDialog(null, "Tên nhà cung cấp không vượt quá 30 ký tự");
            txtTenncc.requestFocus();
            return false;
        }
        else if (txtemail.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null, "Chưa nhập email");
            txtemail.requestFocus();
            return false;
        }
        else if(cl.kiemtraEmail(txtemail.getText()) == false)
        {
            JOptionPane.showMessageDialog(null, "Email không hợp lệ");
            txtemail.requestFocus();
            return false;
        }
        else if (txtphone.getText().equals(""))
        {

            JOptionPane.showMessageDialog(null, "Chưa nhập số điện thoại");
            txtphone.requestFocus();
            return false;
        }
        else if(cl.kiemtraSDT(txtphone.getText())==false)
        {
            JOptionPane.showMessageDialog(null, "Số điện thoại không hợp lệ (11 số) + số 0 đầu");
            txtphone.requestFocus();
            return false;
        }
        else if(cl.kiemtraSo(txtphone.getText())==false)
        {
            JOptionPane.showMessageDialog(null, "Số điện thoại không hợp lệ (nhập số)");
            txtphone.requestFocus();
            return false;
        }

        return true;
    }
    
    public void hienthi()
    {
        JFrame j = new JFrame();
        j.setSize(1000,700);
        j.setLayout(null);
        JPanel p =new nhacungcapGUI();
        p.setBounds(0, 0, 950, 410);
        
        //j.add(g);
        //j.pack();
        j.add(p);
        j.setVisible(true);
    }

    
    public static void main(String[] args) {
        JFrame j = new JFrame();
        j.setSize(1000,700);
        j.setLayout(null);
        JPanel p =new nhacungcapGUI();
        p.setBounds(0, 0, 960, 700);
        //j.add(g);
        //j.pack();
        j.add(p);
        j.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBtn;
    private javax.swing.JLabel changeBtn;
    private javax.swing.JComboBox combobox;
    private javax.swing.JLabel deleteBtn;
    private javax.swing.JLabel docBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel maGiamLb;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTable tablenhacungcap;
    private javax.swing.JLabel thoigianbatdauLb;
    private javax.swing.JLabel thoigianketthucLb;
    private javax.swing.JLabel timkiemIcon;
    private javax.swing.JTextField txtIdncc;
    private javax.swing.JTextField txtTenncc;
    private javax.swing.JTextField txtTimkiem;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
