/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BUS.UserBUS;
import DTO.nhanvienDTO;
import DAO.nhanvienDAO;
import BUS.nhanvienBUS;
import javax.swing.JOptionPane;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MY PC
 */
public class nhanvienGUI extends javax.swing.JPanel {
    DefaultTableModel model =new DefaultTableModel();
    JLabel suaBtn;
    CheckLoi cl = new CheckLoi();
    JTextFieldDateEditor txNgaysinh;
    SimpleDateFormat sp;
    String ngaysinh = "";
    /**
     * Creates new form nhanvienGUI
     */
    public nhanvienGUI() {
        initComponents();
        FormatTable render = new FormatTable();
        render.formatTablenoIcon(tablenhanvien);
        inTable();
        nhanvienBUS bus = new nhanvienBUS();
        txtidnv.setText(bus.loadIdpn());
        txtidnv.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTimkiem = new javax.swing.JTextField();
        combobox = new javax.swing.JComboBox();
        timkiemIcon = new javax.swing.JLabel();
        docBtn = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablenhanvien = new javax.swing.JTable();
        txtluong = new javax.swing.JTextField();
        txtladdress = new javax.swing.JTextField();
        thoigianbatdauLb3 = new javax.swing.JLabel();
        thoigianbatdauLb2 = new javax.swing.JLabel();
        maGiamLb = new javax.swing.JLabel();
        txtidnv = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        thoigianbatdauLb = new javax.swing.JLabel();
        thoigianketthucLb = new javax.swing.JLabel();
        thoigianbatdauLb4 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        changeBtn = new javax.swing.JLabel();
        addBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNgaysinh = new com.toedter.calendar.JDateChooser();

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(950, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 650));

        txtTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimkiemActionPerformed(evt);
            }
        });

        combobox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        combobox.setForeground(new java.awt.Color(0, 51, 255));
        combobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Mã NV", "Fname", "Lname", " " }));

        timkiemIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-35.png"))); // NOI18N
        timkiemIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timkiemIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timkiemIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                timkiemIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                timkiemIconMouseExited(evt);
            }
        });

        docBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-process-35.png"))); // NOI18N
        docBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        docBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                docBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                docBtnMouseExited(evt);
            }
        });

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-delete-35.png"))); // NOI18N
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteBtnMouseExited(evt);
            }
        });

        tablenhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên chương trình", "Thời gian bắt đầu", "Thời gian kết thúc", "Trạng thái", "Nội dung", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablenhanvien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablenhanvien.setRowHeight(20);
        tablenhanvien.setShowVerticalLines(false);
        tablenhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablenhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablenhanvien);

        thoigianbatdauLb3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        thoigianbatdauLb3.setForeground(new java.awt.Color(255, 102, 0));
        thoigianbatdauLb3.setText("Địa chỉ");

        thoigianbatdauLb2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        thoigianbatdauLb2.setForeground(new java.awt.Color(255, 102, 0));
        thoigianbatdauLb2.setText("Lương");

        maGiamLb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        maGiamLb.setForeground(new java.awt.Color(255, 102, 0));
        maGiamLb.setText("ID nhân viên");
        maGiamLb.setMaximumSize(new java.awt.Dimension(81, 25));
        maGiamLb.setPreferredSize(new java.awt.Dimension(81, 25));

        txtidnv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtidnv.setPreferredSize(new java.awt.Dimension(6, 25));
        txtidnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidnvActionPerformed(evt);
            }
        });

        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });

        txtlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlnameActionPerformed(evt);
            }
        });

        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Họ nhân viên");

        thoigianbatdauLb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        thoigianbatdauLb.setForeground(new java.awt.Color(255, 102, 0));
        thoigianbatdauLb.setText("Tên nhân viên");

        thoigianketthucLb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        thoigianketthucLb.setForeground(new java.awt.Color(255, 102, 0));
        thoigianketthucLb.setText("Phone");
        thoigianketthucLb.setPreferredSize(new java.awt.Dimension(124, 25));

        thoigianbatdauLb4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        thoigianbatdauLb4.setForeground(new java.awt.Color(255, 102, 0));
        thoigianbatdauLb4.setText("Email");

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        changeBtn.setBackground(new java.awt.Color(255, 153, 0));
        changeBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        changeBtn.setForeground(new java.awt.Color(255, 255, 255));
        changeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-change-50.png"))); // NOI18N
        changeBtn.setText("Sửa");
        changeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeBtn.setOpaque(true);
        changeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changeBtnMouseExited(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(255, 153, 0));
        addBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add-50.png"))); // NOI18N
        addBtn.setText("Thêm");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.setOpaque(true);
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addBtnMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-account-30.png"))); // NOI18N
        jLabel1.setText("Quản lý nhân viên");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Ngày sinh");

        txtNgaysinh.setPreferredSize(new java.awt.Dimension(91, 25));
        txtNgaysinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNgaysinhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(709, 709, 709)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(changeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timkiemIcon)
                        .addGap(341, 341, 341)
                        .addComponent(docBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(thoigianbatdauLb3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(thoigianbatdauLb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maGiamLb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtidnv, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtFname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(txtlname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(txtladdress, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(93, 93, 93)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(thoigianbatdauLb4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(thoigianbatdauLb2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(thoigianketthucLb, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNgaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thoigianbatdauLb3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timkiemIcon)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(docBtn)
                            .addComponent(deleteBtn))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maGiamLb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thoigianbatdauLb4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thoigianketthucLb, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thoigianbatdauLb, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thoigianbatdauLb2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeBtn)
                            .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(123, 123, 123)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtidnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidnvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidnvActionPerformed

     public void reset()//reset txt field
    {
        txtFname.setText("");
        txtlname.setText("");
        txtphone.setText("");
        txtemail.setText("");       
        txtladdress.setText("");
        txtTimkiem.setText("");
        txtluong.setText("");
        nhanvienBUS bus = new nhanvienBUS();
        txtidnv.setText(bus.loadIdpn());
        inTable();
        
    }
    public void formatDate()//format date theo sql
    {
        try {
            sp = new SimpleDateFormat("yyyy-MM-dd");
            ngaysinh = sp.format(txtNgaysinh.getDate());
        } catch (Exception e) {
            // System.out.println("Lỗi format date");
        }
    }
    public void inTable()//doc du lieu in vao table
    {
        try
        {
        //render();
        nhanvienBUS nvbus = new nhanvienBUS();
        nvbus.docnhanvien();
            int rowCount = model.getRowCount();//remove all row
            for (int i = rowCount - 1; i >= 0; i--) 
            {
                model.removeRow(i);
            }
        Vector header = new Vector();
        header.add("ID NV");
        header.add("Fname");
        header.add("Lname");
        header.add("Phone");
        header.add("Email");
        header.add("Address");
        header.add("Ngày sinh");
        header.add("Lương");
        header.add("Trạng thái");
        if (model.getRowCount()==0)
            { 
                model=new DefaultTableModel(header,0);
            } 
        for(nhanvienDTO nv : nhanvienBUS.dsnv)
        {
                Vector row = new Vector();
                row.add(nv.getIdnv());
                row.add(nv.getFname());
                row.add(nv.getLname());
                row.add(nv.getPhone());
                row.add(nv.getEmail());                
                row.add(nv.getAddress());
                row.add(nv.getNgaysinh());
                row.add(nv.getLuong());
                row.add(formatTrangthai(nv.getTrangthai()));
                
                model.addRow(row);
        }
        //add model to jtable
        tablenhanvien.setModel(model);
        
        } catch(Exception e)
        {
            System.out.println(e);
            System.out.println("Lỗi đọc nhân viên");
        }
    }
    public String formatTrangthai(String a)
    {
        if(a.equals("1"))
        {
            return "Còn làm";
        }
        else 
        {
            return "Không còn làm";
        }
    }
    public boolean kiemtra()
    {
        Date now = new Date();
        int cp = now.getYear() - txtNgaysinh.getDate().getYear();
        if(txtidnv.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Chưa nhập mã nhân viên");
            txtidnv.requestFocus();
            return false;
        }
        
        else if (txtFname.getText().equals("")  )
        {
            JOptionPane.showMessageDialog(null, "Chưa nhập First name");
            txtFname.requestFocus();
            return false;
        }
        else if(cl.kiemtraSokitu(txtFname.getText(), 30)==false)
        {
            JOptionPane.showMessageDialog(null, "First name không vượt quá 30 ký tự");
            txtFname.requestFocus();
            return false;
        }
        else if (txtlname.getText().equals("")  )
        {
            JOptionPane.showMessageDialog(null, "Chưa nhập Last name");
            txtlname.requestFocus();
            return false;
        }
        else if(cl.kiemtraSokitu(txtlname.getText(), 30)==false)
        {
            JOptionPane.showMessageDialog(null, "Last Name không vượt quá 30 ký tự");
            txtlname.requestFocus();
            return false;
        }
        else if (txtladdress.getText().equals(""))
        {

            JOptionPane.showMessageDialog(null, "Chưa nhập địa chỉ");
            txtladdress.requestFocus();
            return false;
        }
        else if (cl.kiemtraSokitu(txtladdress.getText(),200) == false)
        {
            JOptionPane.showMessageDialog(null, "Dia chi khong vuot qua 200 ki tu");
            txtladdress.requestFocus();
            return false;
        }
        else if (txtemail.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null, "Chưa nhập email");
            txtemail.requestFocus();
            return false;
        }
        else if(cl.kiemtraEmail(txtemail.getText()) == false)
        {
            JOptionPane.showMessageDialog(null, "Email không hợp lệ");
            txtemail.requestFocus();
            return false;
        }
        else if (txtphone.getText().equals(""))
        {

            JOptionPane.showMessageDialog(null, "Chưa nhập số điện thoại");
            txtphone.requestFocus();
            return false;
        }
        else if(cl.kiemtraSDT(txtphone.getText())==false)
        {
            JOptionPane.showMessageDialog(null, "Số điện thoại không hợp lệ (11 số) + số 0 đầu");
            txtphone.requestFocus();
            return false;
        }
        else if(cl.kiemtraSo(txtphone.getText())==false)
        {
            JOptionPane.showMessageDialog(null, "Số điện thoại không hợp lệ (nhập số)");
            txtphone.requestFocus();
            return false;
        }
        else if (txtluong.getText().equals(""))
        {

            JOptionPane.showMessageDialog(null, "Chưa nhập lương");
            txtluong.requestFocus();
            return false;
        }
        else if(cl.kiemtraSo(txtluong.getText())==false)
        {
            JOptionPane.showMessageDialog(null, "Nhập số vào lương");
            txtluong.requestFocus();
            return false;
        }
        else if(cl.kiemtraSokitu(txtluong.getText(), 11)==false)
        {
            JOptionPane.showMessageDialog(null, "Luong qua lon");
            txtluong.requestFocus();
            return false;
        }
        else if(cl.kiemtraSophay(txtluong.getText()) == false)
        {
            JOptionPane.showMessageDialog(null, "Nhap dung kieu int");
            txtluong.requestFocus();
            return false;
        } 
        
        else if(cp < 18 || cp > 45)
        {
            JOptionPane.showMessageDialog(null, "Tuổi nhân viên phải từ 18 đến 45 ");
            return false;
        }
        return true;
    }
    
    public void hienthi()
    {
        JFrame j = new JFrame();
        j.setSize(1000,700);
        j.setLayout(null);
        JPanel p =new nhanvienGUI();
        p.setBounds(0, 0, 950, 410);
        
        //j.add(g);
        //j.pack();
        j.add(p);
        j.setVisible(true);
    }
    
    public void timkiem(ArrayList<nhanvienDTO> arr)
    {
        //hien thong tin tim kiem
    int rowCount = model.getRowCount();//remove all row
            for (int i = rowCount - 1; i >= 0; i--) {
                model.removeRow(i);
            }
        Vector header = new Vector();
        header.add("ID NV");
        header.add("Fname");
        header.add("Lname");
        header.add("Phone");
        header.add("Email");
        header.add("Loại NV");
        header.add("Lương");
        header.add("Trạng thái");
        if (model.getRowCount()==0)
            { 
                model=new DefaultTableModel(header,0);
            } 
        for(nhanvienDTO nv : arr)//duyet arr chua cac ket qua tìm kiếm
        {
                Vector row = new Vector();
                row.add(nv.getIdnv());
                row.add(nv.getFname());
                row.add(nv.getLname());
                row.add(nv.getPhone());
                row.add(nv.getEmail());
                row.add(nv.getAddress());
                row.add(nv.getLoainv());
                row.add(nv.getLuong());
                row.add(formatTrangthai(nv.getTrangthai()));
                model.addRow(row);
        }
        //add model to jtable
        tablenhanvien.setModel(model);
    }
    
    
    
    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked

        nhanvienBUS nvbus = new nhanvienBUS();
        nvbus.docnhanvien();
        formatDate();
        try
        {
            nhanvienDTO nvdto = new nhanvienDTO();
            boolean ok = false;
            
            if(kiemtra())
            {
                ok = true;
            }
            if(ok)
            {

                nhanvienDTO nv = new nhanvienDTO();
                nv.setIdnv(txtidnv.getText());
                nv.setFname(txtFname.getText());
                nv.setLname(txtlname.getText());
                nv.setPhone(txtphone.getText());
                nv.setEmail(txtemail.getText());
                nv.setAddress(txtladdress.getText());
                nv.setNgaysinh(ngaysinh);
                nv.setLuong((Integer.valueOf(txtluong.getText())));
                nv.setTrangthai("1");
                nvbus.themnhanvien(nv);

                //Jtable
                Vector header = new Vector();
                header.add("ID NV");
                header.add("Fname");
                header.add("Lname");
                header.add("Phone");
                header.add("Email");
                header.add("Address");
                header.add("Ngày sinh");
                header.add("Lương");
                header.add("Trạng thái");

                if (model.getRowCount() == 0) 
                {
                    model = new DefaultTableModel(header, 0);
                }
                Vector row = new Vector();
                row.add(nv.getIdnv());
                row.add(nv.getFname());
                row.add(nv.getLname());
                row.add(nv.getPhone());
                row.add(nv.getEmail());
                row.add(nv.getAddress());
                row.add(nv.getNgaysinh());
                row.add(nv.getLuong());
                row.add("Còn làm");
                model.addRow(row);
                //add model to jtable
                tablenhanvien.setModel(model);
                //                    System.out.println(begin);
                //                    System.out.println(end);
                JOptionPane.showMessageDialog(null, "Thêm nhân viên thành công");
                
                reset();

            }
        } catch (Exception e)
        {   
            System.out.println(e);
            System.out.println("Lỗi thêm nhân viên");
            
        }
    }//GEN-LAST:event_addBtnMouseClicked

    private void addBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseEntered
        // TODO add your handling code here:
        //addbtn
        addBtn.setBackground(Color.blue);
    }//GEN-LAST:event_addBtnMouseEntered

    private void addBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseExited
        // TODO add your handling code here:
        addBtn.setBackground(new Color(255, 153, 0));
    }//GEN-LAST:event_addBtnMouseExited

    private void changeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeBtnMouseClicked
        // TODO add your handling code here:
        //sua btn click
        try
        {
            if(tablenhanvien.getSelectionModel().isSelectionEmpty())//neu khong chọn row trong table
            {
                JOptionPane.showMessageDialog(null, "Chưa chọn mã cần sửa");
            } else
            {
                int  i=tablenhanvien.getSelectedRow();
                nhanvienDTO nv=new nhanvienDTO();
                formatDate();
                nv.setIdnv(txtidnv.getText());
                nv.setFname(txtFname.getText());
                nv.setLname(txtlname.getText());
                nv.setPhone(txtphone.getText());
                nv.setEmail(txtemail.getText());
                nv.setAddress(txtladdress.getText());
                nv.setNgaysinh(ngaysinh);
                nv.setLuong(Integer.valueOf(txtluong.getText()));
                nv.setTrangthai("1");
                //cap nhập dsgg
                nhanvienBUS nvbus = new nhanvienBUS();
                nvbus.suanhanvien(nv);
                //System.out.println(ChuongTrinhGiamBUS.dsgiamgia.get(i));
                //truyen vao table bang arr cua bus
                model.setValueAt(nv.getIdnv(), i, 0);
                model.setValueAt(nv.getFname(), i, 1);
                model.setValueAt(nv.getLname(), i, 2);
                model.setValueAt(nv.getPhone(), i, 3);
                model.setValueAt(nv.getEmail(), i, 4);
                model.setValueAt(nv.getAddress(), i, 5);
                model.setValueAt(nv.getNgaysinh(), i, 6);
                model.setValueAt(nv.getLuong(), i, 7);
                model.setValueAt("Còn làm", i, 8);

                tablenhanvien.setModel(model);
                JOptionPane.showMessageDialog(null, "Sửa thành công");
                reset();
            }
        } catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_changeBtnMouseClicked

    private void changeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeBtnMouseEntered
        // TODO add your handling code here:\
        changeBtn.setBackground(Color.blue);
    }//GEN-LAST:event_changeBtnMouseEntered

    private void changeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeBtnMouseExited
        // TODO add your handling code here:
        changeBtn.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_changeBtnMouseExited

    private void txtTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimkiemActionPerformed

    private void timkiemIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiemIconMouseClicked
        // TODO add your handling code here:
        nhanvienBUS nvbus = new nhanvienBUS();
        if(combobox.getSelectedItem().equals("All"))
        {
            //thêm txt cần tìm vào hàm timtheo... của bus sau đó truyền hàm đó vào hàm timkiem ở gui de in len jtable
            timkiem(nvbus.timtheoAll(txtTimkiem.getText()));
        }
        if(combobox.getSelectedItem().equals("Mã NV"))
        {
            //thêm txt cần tìm vào hàm timtheo... của bus sau đó truyền hàm đó vào hàm timkiem ở gui de in len jtable
            timkiem(nvbus.timtheoMa(txtTimkiem.getText()));
        }
        if(combobox.getSelectedItem().equals("Fname"))
        {
            //thêm txt cần tìm vào hàm timtheo... của bus sau đó truyền hàm đó vào hàm timkiem ở gui de in len jtable
            timkiem(nvbus.timtheoFname(txtTimkiem.getText()));
        }
        if(combobox.getSelectedItem().equals("Lname"))
        {
            //thêm txt cần tìm vào hàm timtheo... của bus sau đó truyền hàm đó vào hàm timkiem ở gui de in len jtable
            timkiem(nvbus.timtheoLname(txtTimkiem.getText()));
        }
    }//GEN-LAST:event_timkiemIconMouseClicked

    private void timkiemIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiemIconMouseEntered
        // TODO add your handling code here:
        timkiemIcon.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/search.png");
        timkiemIcon.setIcon(logo);
    }//GEN-LAST:event_timkiemIconMouseEntered

    private void timkiemIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiemIconMouseExited
        // TODO add your handling code here:
        timkiemIcon.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-search-35.png");
        timkiemIcon.setIcon(logo);
    }//GEN-LAST:event_timkiemIconMouseExited

    private void docBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docBtnMouseClicked
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_docBtnMouseClicked

    private void docBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docBtnMouseEntered
        // TODO add your handling code here:
        docBtn.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-process-35 (1).png");
        docBtn.setIcon(logo);
    }//GEN-LAST:event_docBtnMouseEntered

    private void docBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docBtnMouseExited
        // TODO add your handling code here:
        docBtn.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-process-35.png");
        docBtn.setIcon(logo);
    }//GEN-LAST:event_docBtnMouseExited

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        // TODO add your handling code here:
        //delete click
        try
        {
            if(tablenhanvien.getSelectionModel().isSelectionEmpty())//neu khong chọn row trong table
            {
                JOptionPane.showMessageDialog(null, "Chưa chọn nhân viên cần xóa");
            }
            else
            {
                int yn = JOptionPane.showConfirmDialog(
                    null,
                    "Bạn có chắc xóa nhân viên này?",
                    "Are you sure?",
                    JOptionPane.YES_NO_OPTION);
                if (yn == JOptionPane.YES_OPTION)
                {
                    int  i=tablenhanvien.getSelectedRow();
                    if(tablenhanvien.getValueAt(i, 0).equals(OverallFrame.currentIdnv))
                    {
                        JOptionPane.showMessageDialog(null, "Đây là bạn!!!");
                    }
                    else
                    {
                    

                    nhanvienDTO nv = new nhanvienDTO();
                    nv.setIdnv(txtidnv.getText());

                    //cap nhập dsgg

                    nhanvienBUS bus = new nhanvienBUS();
                    bus.xoanhanvien(nv);
                    //remove o table
                    //xoa user cua nhan vien
                    UserBUS ubus = new UserBUS();
                    ubus.xoaUsertheonhanvien(txtidnv.getText());
                    model.removeRow(i);
                    reset();
                    //tableGiamgia.setModel(model);
                    }
                }
            }

        } catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void deleteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseEntered
        // TODO add your handling code here:
        deleteBtn.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-delete-35 (1).png");
        deleteBtn.setIcon(logo);
    }//GEN-LAST:event_deleteBtnMouseEntered

    private void deleteBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseExited
        // TODO add your handling code here:
        deleteBtn.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-delete-35.png");
        deleteBtn.setIcon(logo);
    }//GEN-LAST:event_deleteBtnMouseExited

    private void tablenhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablenhanvienMouseClicked
        // TODO add your handling code here:
        try
        {
            int  i=tablenhanvien.getSelectedRow();
            if(i>=0)
            {
                txtidnv.setEditable(false);//ko cho dien mã
                nhanvienDTO nv =new nhanvienDTO();
                //ct = ChuongTrinhGiamBUS.dsgiamgia.get(i);    //goi arr bus lay gia trị
                txtidnv.setText((String)tablenhanvien.getValueAt(i, 0));
                txtFname.setText((String)tablenhanvien.getValueAt(i, 1));
                txtlname.setText((String)tablenhanvien.getValueAt(i, 2));
                txtphone.setText(String.valueOf(tablenhanvien.getValueAt(i, 3)));
                txtemail.setText((String)tablenhanvien.getValueAt(i, 4));
                txtladdress.setText((String)tablenhanvien.getValueAt(i, 5));
                Date e = new SimpleDateFormat("yyyy-MM-dd").parse((String) tablenhanvien.getValueAt(i, 6).toString());
                txtNgaysinh.setDate(e);
                txtluong.setText(String.valueOf(tablenhanvien.getValueAt(i, 7)));
                //format theo kiểu của jdatechooser

            }
        } catch (Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_tablenhanvienMouseClicked

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        


        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        
// TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnameActionPerformed
              // TODO add your handling code here:
    }//GEN-LAST:event_txtlnameActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtNgaysinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNgaysinhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaysinhMouseClicked

    public static void main(String[] args) 
    {
        JFrame j = new JFrame();
        j.setSize(960,700);
        j.setLayout(null);
        JPanel p =new nhanvienGUI();
        p.setBounds(0, 0, 960, 700);
        //j.add(g);
        //j.pack();
        j.add(p);
        j.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBtn;
    private javax.swing.JLabel changeBtn;
    private javax.swing.JComboBox combobox;
    private javax.swing.JLabel deleteBtn;
    private javax.swing.JLabel docBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maGiamLb;
    private javax.swing.JTable tablenhanvien;
    private javax.swing.JLabel thoigianbatdauLb;
    private javax.swing.JLabel thoigianbatdauLb2;
    private javax.swing.JLabel thoigianbatdauLb3;
    private javax.swing.JLabel thoigianbatdauLb4;
    private javax.swing.JLabel thoigianketthucLb;
    private javax.swing.JLabel timkiemIcon;
    private javax.swing.JTextField txtFname;
    private com.toedter.calendar.JDateChooser txtNgaysinh;
    private javax.swing.JTextField txtTimkiem;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtidnv;
    private javax.swing.JTextField txtladdress;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtluong;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
