/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BUS.MonanBUS;
import BUS.chitietphieunhapBUS;
import DTO.phieunhapDTO;
import DTO.nhacungcapDTO;
import DTO.nhanvienDTO;
import DAO.nhacungcapDAO;
import DAO.nhanvienDAO;
import DAO.phieunhapDAO;
import BUS.phieunhapBUS;
import BUS.nhacungcapBUS;
import BUS.nhanvienBUS;
import DTO.chitietphieunhapDTO;
import javax.swing.JOptionPane;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MY PC
 */
public class QuanLyPhieuNhap extends javax.swing.JPanel 
{
    DefaultTableModel model =new DefaultTableModel();
    DefaultTableModel modelTb2 =new DefaultTableModel();
    JLabel suaBtn;
    JTextFieldDateEditor txngnhap;
    public static String layidpn;
    String ngnhap = "";
    
    String trangthai ="";
    SimpleDateFormat sp;
    /**
     * Creates new form phieunhapGUI
     */
    public QuanLyPhieuNhap() 
    {
        initComponents();
        FormatTable render = new FormatTable();
        render.formatTablenoIcon(tablephieunhap);
        render.formatTablenoIcon(tableChitiet);
        inTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablephieunhap = new javax.swing.JTable();
        deleteBtn = new javax.swing.JLabel();
        docBtn = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableChitiet = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ChitietBtn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 204));
        setMaximumSize(new java.awt.Dimension(950, 650));
        setPreferredSize(new java.awt.Dimension(950, 650));

        leftPanel.setBackground(new java.awt.Color(0, 255, 204));

        tablephieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID PN", "ID NCC", "ID NV", "Ngày nhập", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablephieunhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablephieunhap.setRowHeight(20);
        tablephieunhap.setShowVerticalLines(false);
        tablephieunhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablephieunhapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablephieunhap);

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-delete-35.png"))); // NOI18N
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteBtnMouseExited(evt);
            }
        });

        docBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-process-35.png"))); // NOI18N
        docBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        docBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                docBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                docBtnMouseExited(evt);
            }
        });

        tableChitiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id phiếu nhập", "Id món", "Số lượng", "Giá nhập", "Thành tiền"
            }
        ));
        jScrollPane2.setViewportView(tableChitiet);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Danh sách phiếu nhập");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Chi tiết phiếu nhập");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-down-button-30 (1).png"))); // NOI18N
        jButton1.setText("In phiếu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(docBtn)
                .addGap(18, 18, 18)
                .addComponent(deleteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(201, 201, 201))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(98, 98, 98))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(docBtn)
                    .addComponent(deleteBtn))
                .addGap(18, 18, 18)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-shopping-cart-50.png"))); // NOI18N
        jLabel3.setText("Lịch sử nhập hàng");

        ChitietBtn.setBackground(new java.awt.Color(255, 153, 0));
        ChitietBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ChitietBtn.setForeground(new java.awt.Color(255, 255, 255));
        ChitietBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChitietBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-back-arrow-30.png"))); // NOI18N
        ChitietBtn.setText("Quay lại");
        ChitietBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChitietBtn.setOpaque(true);
        ChitietBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChitietBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChitietBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChitietBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(ChitietBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(382, 382, 382))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ChitietBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void inTable()//doc du lieu in vao table
    {
        try
        {
        //render();
        phieunhapBUS bus = new phieunhapBUS();
        bus.docphieunhap(OverallFrame.currentIdnv);
            int rowCount = model.getRowCount();//remove all row
            for (int i = rowCount - 1; i >= 0; i--) 
            {
                model.removeRow(i);
            }
        Vector header = new Vector();
        header.add("ID PN");
        header.add("ID NCC");
        header.add("ID NV");
        header.add("Ngày nhập");
        header.add("Tổng tiền");
        header.add("Trạng thái");
        if (model.getRowCount()==0)
            { 
                model=new DefaultTableModel(header,0);
            } 
        for(phieunhapDTO pn : phieunhapBUS.dspn123)
        {
                Vector row = new Vector();
                row.add(pn.getIdpn());
                row.add(pn.getIdncc());
                row.add(pn.getIdnv());
                row.add(pn.getNgaynhap());
                row.add(pn.getTongtien());                
                row.add(format(pn.getTrangthai()));
                
                model.addRow(row);
        }
        //add model to jtable
        tablephieunhap.setModel(model);
        
        } catch(Exception e)
        {
            System.out.println(e);
            System.out.println("Lỗi đọc phiếu nhập");
        }
    }
    public String format(String a)
    {
        return "Thành công";
    }
    public void docChitiet()
    {
        int j = tablephieunhap.getSelectedRow();
        chitietphieunhapBUS bus = new chitietphieunhapBUS();
        chitietphieunhapDTO dto = new chitietphieunhapDTO();
        bus.docChitiet((String)tablephieunhap.getValueAt(j, 0));
        
            int rowCount = modelTb2.getRowCount();//remove all row
            for (int i = rowCount - 1; i >= 0; i--) {
                modelTb2.removeRow(i);
            }
            Vector header = new Vector();
        header.add("Id phiếu nhập");
        header.add("Id Món");
        header.add("Số lượng");
        header.add("Giá nhập");
        header.add("Thành tiền");
        
        if (modelTb2.getRowCount()==0)
            { 
                modelTb2=new DefaultTableModel(header,0);
            } 
        for(chitietphieunhapDTO ct : chitietphieunhapBUS.dschitiet)
        {
            
            Vector row = new Vector();
                row.add(ct.getIdpn());
                row.add(ct.getIdmon());
                row.add(ct.getSoluong());
                row.add(ct.getGianhap());
                row.add(ct.getThanhtien());
                modelTb2.addRow(row);
        }
        tableChitiet.setModel(modelTb2);
    }
    
    
    
    public void hienthi()
    {
        JFrame j = new JFrame();
        j.setSize(1000,700);
        j.setLayout(null);
        JPanel p =new QuanLyPhieuNhap();
        p.setBounds(0, 0, 950, 410);
        
        //j.add(g);
        //j.pack();
        j.add(p);
        j.setVisible(true);
    }
    
    
    private void docBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docBtnMouseClicked
        // TODO add your handling code here:
        inTable();
        int rowCount = modelTb2.getRowCount();//remove all row
            for (int i = rowCount - 1; i >= 0; i--) 
            {
                modelTb2.removeRow(i);
            }
    }//GEN-LAST:event_docBtnMouseClicked

    private void docBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docBtnMouseEntered
        // TODO add your handling code here:
        docBtn.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-process-35 (1).png");
        docBtn.setIcon(logo);
    }//GEN-LAST:event_docBtnMouseEntered

    private void docBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docBtnMouseExited
        // TODO add your handling code here:
        docBtn.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-process-35.png");
        docBtn.setIcon(logo);
    }//GEN-LAST:event_docBtnMouseExited

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        // TODO add your handling code here:
        //delete click
        try
        {
            if(tablephieunhap.getSelectionModel().isSelectionEmpty())//neu khong chọn row trong table
            {
                JOptionPane.showMessageDialog(null, "Chưa chọn mã cần xóa");
            }
            else
            {
                int yn = JOptionPane.showConfirmDialog(
                    null,
                    "Bạn có chắc hủy phiếu nhập này?",
                    "Are you sure?",
                    JOptionPane.YES_NO_OPTION);
                if (yn == JOptionPane.YES_OPTION)
                {
                    int  i=tablephieunhap.getSelectedRow();

                    phieunhapDTO pn = new phieunhapDTO();
                    //trừ tồn kho
                    int rowCount = modelTb2.getRowCount();
                    for(int k = 0; k< rowCount; k++)
                    {
                        MonanBUS monan = new MonanBUS();
                        monan.truTonkho((int)(tableChitiet.getValueAt(k, 2)), 
                                (String)tableChitiet.getValueAt(k,1)); 
                    }
                    phieunhapBUS bus = new phieunhapBUS();
                    bus.xoaphieunhap((String)tableChitiet.getValueAt(i,0));
                    //remove o table
                    model.removeRow(i);
                    int rowCount1 = modelTb2.getRowCount();//remove all row
                    for (int dem = rowCount1 - 1; dem >= 0; dem--) {
                        modelTb2.removeRow(dem);
                    }
                    //tableGiamgia.setModel(model);

                }
            }

        } catch(Exception e)
        {
            System.out.println(e);
            System.out.println("Lỗi xóa");
        }
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void deleteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseEntered
        // TODO add your handling code here:
        deleteBtn.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-delete-35 (1).png");
        deleteBtn.setIcon(logo);
    }//GEN-LAST:event_deleteBtnMouseEntered

    private void deleteBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseExited
        // TODO add your handling code here:
        deleteBtn.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-delete-35.png");
        deleteBtn.setIcon(logo);
    }//GEN-LAST:event_deleteBtnMouseExited

    private void tablephieunhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablephieunhapMouseClicked
        // TODO add your handling code here:
        docChitiet();

    }//GEN-LAST:event_tablephieunhapMouseClicked

    private void ChitietBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChitietBtnMouseClicked
        // TODO add your handling code here:
        OverallFrame.changeMainInfo(9);
    }//GEN-LAST:event_ChitietBtnMouseClicked

    private void ChitietBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChitietBtnMouseEntered
        // TODO add your handling code here:
        ChitietBtn.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-back-arrow-30.png");
        ChitietBtn.setIcon(logo);
        ChitietBtn.setBackground(Color.blue);
    }//GEN-LAST:event_ChitietBtnMouseEntered

    private void ChitietBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChitietBtnMouseExited
        // TODO add your handling code here:
        ChitietBtn.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-back-arrow-30.png");
        ChitietBtn.setIcon(logo);
        ChitietBtn.setBackground(new Color(255, 153, 0));
    }//GEN-LAST:event_ChitietBtnMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        JFileChooser chooser = new JFileChooser();
//        int i = chooser.showSaveDialog(chooser);
//        if (i == JFileChooser.APPROVE_OPTION) {
//            File file = chooser.getSelectedFile();
//            try {
//                System.out.println(file);
//                Writer bwrite = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(file), StandardCharsets.UTF_8));
//                DefaultTableModel model = (DefaultTableModel) tableChitiet.getModel();
//                // ten Cot
//                for (int j = 0; j < tableChitiet.getColumnCount(); j++) {
//                    bwrite.write(model.getColumnName(j) + "\t");
//                }
//                bwrite.write("\n");
//                // Lay du lieu dong
//                for (int j = 0; j < tableChitiet.getRowCount(); j++) {
//                    for (int k = 0; k < tableChitiet.getColumnCount(); k++) {
//                        bwrite.write(model.getValueAt(j, k) + "\t");
//                    }
//                    bwrite.write("\n");
//                }
//                bwrite.close();
//                JOptionPane.showMessageDialog(null, "Lưu file thành công!");
//            } catch (Exception e2) {
//                System.out.println(e2);
//                JOptionPane.showMessageDialog(null, "Lỗi khi lưu file!");
//            }
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public static void main(String[] args) 
    {
        JFrame j = new JFrame();
        j.setSize(960,700);
        j.setLayout(null);
        JPanel p =new QuanLyPhieuNhap();
        p.setBounds(0, 0, 960, 700);
        //j.add(g);
        //j.pack();
        j.add(p);
        j.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChitietBtn;
    private javax.swing.JLabel deleteBtn;
    private javax.swing.JLabel docBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JTable tableChitiet;
    private javax.swing.JTable tablephieunhap;
    // End of variables declaration//GEN-END:variables


    }
