/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.MonanBUS;
import DTO.LoaimonanDTO;
import DTO.MonanDTO;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Nam
 */
public class themSanphamDialog extends javax.swing.JFrame {
    DefaultComboBoxModel model = new DefaultComboBoxModel();
    public final String pathImg = "C:\\Users\\Nam\\Desktop\\Nhom2_Nam_Bao\\source code\\DoanJvVer2\\src\\img\\";
    public static File fileName;
    /**
     * Creates new form themSanphamDialog
     */
    public themSanphamDialog() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        lbnhacc.setText(PhieuNhapGUI.idNcc);
        setCombobox();
        txtIdsp.setEditable(false);
        
    }
    public void setCombobox()// layá danh sach loai
    {
        MonanBUS bus = new MonanBUS();
        bus.docDsloaimonan();
        for(LoaimonanDTO a : MonanBUS.dsloaimonan)
        {
            model.addElement(a.getIdloai() +"- "+ a.getLoaimon());
        }
        cbLoai.setModel(model);       
        txtIdsp.setText(bus.getIDmon());//tự gán id mon theo nha cung cap
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbnhacc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIdsp = new javax.swing.JTextField();
        txtTensp = new javax.swing.JTextField();
        cbLoai = new javax.swing.JComboBox();
        xacnhanBtn = new javax.swing.JButton();
        lbImg = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Thêm sản phẩm mới từ nhà cung cấp");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thêm sản phẩm mới từ nhà cung cấp");

        lbnhacc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbnhacc.setForeground(new java.awt.Color(255, 102, 0));
        lbnhacc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbnhacc.setText("null");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Id Sản phẩm");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("Loại sản phẩm");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("Tên sản phẩm");

        txtIdsp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdspActionPerformed(evt);
            }
        });

        txtTensp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        cbLoai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbLoai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        xacnhanBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xacnhanBtn.setForeground(new java.awt.Color(255, 0, 0));
        xacnhanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addicon1.png"))); // NOI18N
        xacnhanBtn.setText("Xác nhận");
        xacnhanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xacnhanBtnActionPerformed(evt);
            }
        });

        lbImg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbImg.setForeground(new java.awt.Color(255, 51, 0));
        lbImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImg.setText("Click here to add img");
        lbImg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        lbImg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbImg.setOpaque(true);
        lbImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbImgMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(xacnhanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lbImg, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdsp, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbnhacc, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(79, 90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbnhacc)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtIdsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbImg, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(xacnhanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdspActionPerformed

    private void xacnhanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xacnhanBtnActionPerformed
        // TODO add your handling code here:
        if(txtTensp.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Tên sản phẩm không được để trống");
        } else if(fileName == null)
        {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn hình ảnh");
        } else {
        MonanDTO dto = new MonanDTO();
        String a = (String)cbLoai.getSelectedItem();
        dto.setIdmon(txtIdsp.getText());
        dto.setIdloai(Integer.parseInt(a.substring(0, 1)));
        dto.setTenmon(txtTensp.getText());
        dto.setDongia(0);
        dto.setTonkho(0);
        dto.setSoluongdaban(0);
        dto.setTrangthai("1");
        dto.setCogiamgia("0");
        MonanBUS bus = new MonanBUS();
        bus.addMonan(dto);
        
        //chuyen hinh ảnh vao kho ảnh cua pahn mem
        String duoiFile = fileName.getName().split("\\.")[1];
        File filemoi = new File(pathImg + txtIdsp.getText() + "." +duoiFile);//dinh dang file bang ma san pham
        fileName.renameTo(filemoi);
        JOptionPane.showMessageDialog(null, "Thêm sản phẩm mới thành công");
        this.dispose();
        }
    }//GEN-LAST:event_xacnhanBtnActionPerformed

    private void lbImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbImgMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int i = chooser.showSaveDialog(chooser);
        if (i == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            try {
                String chinhViethoa = file.getName().split("\\.")[1].toLowerCase();//chỉnh lại kieu ko viet hoa
                if(!chinhViethoa.equals("png") 
                        && !chinhViethoa.equals("jpg"))//check dinh dang file
                {
                    System.out.println("Đây không phải là ảnh");
                } 
                else {
                BufferedImage myPicture = ImageIO.read(file);
                ImageIcon img = new ImageIcon(myPicture.getScaledInstance(190, 190, Image.SCALE_FAST));
                lbImg.setText("");
                lbImg.setIcon(img);
                fileName = file;

//                File rm = new File("C:\\Users\\Nam\\Desktop\\anh\\New folder\\a.png");
//                file.renameTo(rm);
                }
            } catch(Exception e)
            {}
        }
    }//GEN-LAST:event_lbImgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(themSanphamDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(themSanphamDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(themSanphamDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(themSanphamDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new themSanphamDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbImg;
    private javax.swing.JLabel lbnhacc;
    private javax.swing.JTextField txtIdsp;
    private javax.swing.JTextField txtTensp;
    private javax.swing.JButton xacnhanBtn;
    // End of variables declaration//GEN-END:variables
}
